name: OSX build

on:
  push:
    branches: [ main, dev ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:

    name: Build on macos-latest
    runs-on: macos-latest

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.18.x'

    - name: Use cmake
      run: cmake --version

    - uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Generate Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: blade-macos-${{ github.run_id }}
        path: ${{github.workspace}}/build/bin
