name: "Windows (MinGW64) build"

on:
  push:
    branches: [ main, dev ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: msys2 {0}

jobs:
  build:
    name: Build on windows-latest
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          base-devel
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-toolchain

    - uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -B '${{github.workspace}}' -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_SYSTEM_VERSION=10.0.18362

    - name: Build
      run: cmake --build '${{github.workspace}}' --config ${{env.BUILD_TYPE}}

    - name: Generate Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: blade-windows-mingw64-${{ github.run_id }}
        path: ${{github.workspace}}/blade
